### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by xinjicong** [cliang1453/BOND#14]
when i was running my own dataset, the following problem arised:
Traceback (most recent call last):
  File "run_self_training_ner.py", line 752, in <module>
    main()
  File "run_self_training_ner.py", line 681, in main
    model, global_step, tr_loss, best_dev, best_test = train(args, train_dataset, model_class, config, tokenizer, labels, pad_token_label_id)
  File "run_self_training_ner.py", line 353, in train
    loss.backward()
  File "/anaconda3/envs/bond/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/anaconda3/envs/bond/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

Are there any specific requirements for the data format, such as the sentence length?

**Comment by xinjicong** [comment]
Sorry to bother, something is wrong with my data path. Now it works.
